ALTER TABLE public.marketing_tasks
ADD COLUMN IF NOT EXISTS task_code TEXT UNIQUE,
ADD COLUMN IF NOT EXISTS supporter_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS start_date DATE,
ADD COLUMN IF NOT EXISTS result_links TEXT,
ADD COLUMN IF NOT EXISTS parent_id UUID REFERENCES public.marketing_tasks(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS format TEXT,
ADD COLUMN IF NOT EXISTS platform TEXT,
ADD COLUMN IF NOT EXISTS completion_pct INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS completion_date DATE;
